import Head from "next/head";
import Index from "../components/home/designGoals";
import { KanyeProvider } from "../components/provider/provider";

export default function Home() {
  return (
    <KanyeProvider>
      {" "}
      <div className="">
        <Head>
          <title>Namenmonument Tropenmuseum</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="">
          <Index />
        </main>
      </div>
    </KanyeProvider>
  );
}
