import Head from "next/head";
import Index from "../components/home/home";
import Index2 from "../components/home/homever2";
import styles from "../styles/Home.module.css";
import { KanyeProvider } from "../components/provider/provider";

export default function Home() {
  return (
    <KanyeProvider>
      {" "}
      <div className="">
        <Head>
          <title>Namenmonument Tropenmuseum</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="">
          <Index2 />
        </main>
      </div>
    </KanyeProvider>
  );
}
